#!/bin/bash

# ============================================================================
# Initialize Azure Deployment Configuration
# ============================================================================
# 
# This script helps you set up your deployment configuration securely
# without hardcoding sensitive information
#
# Usage: ./.azure/init-config.sh
#
# ============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}→${NC} $1"; }
log_warning() { echo -e "${YELLOW}⚠${NC} $1"; }
log_success() { echo -e "${GREEN}✓${NC} $1"; }

# ============================================================================
# Check prerequisites
# ============================================================================
echo ""
echo -e "${BLUE}Azure Deployment Configuration Wizard${NC}"
echo "========================================"
echo ""

if ! command -v az &> /dev/null; then
  echo -e "${RED}✗ Azure CLI not installed${NC}"
  echo "Install with: brew install azure-cli"
  exit 1
fi
log_success "Azure CLI installed"

if ! az account show &> /dev/null; then
  echo -e "${YELLOW}⚠ Not logged into Azure${NC}"
  echo "Run 'az login' to authenticate"
  exit 1
fi
log_success "Authenticated to Azure"

echo ""
log_info "Detecting Azure resources..."

# Get current subscription
CURRENT_SUB=$(az account show --query "{id:id, name:displayName}" -o json)
SUB_ID=$(echo "$CURRENT_SUB" | jq -r '.id')
SUB_NAME=$(echo "$CURRENT_SUB" | jq -r '.name')

echo "  Subscription: $SUB_NAME"
echo "  ID: $SUB_ID"

echo ""
log_info "Available resource groups:"

RG_LIST=$(az group list --query "[].{name:name, location:location}" -o json)
RG_COUNT=$(echo "$RG_LIST" | jq 'length')

if [ "$RG_COUNT" -eq 0 ]; then
  echo "  (none found)"
  exit 1
fi

echo "$RG_LIST" | jq -r '.[] | "  \(.name) (location: \(.location))"'

echo ""
read -p "Enter resource group name: " RESOURCE_GROUP

if ! az group show --name "$RESOURCE_GROUP" &> /dev/null; then
  log_warning "Resource group not found: $RESOURCE_GROUP"
  exit 1
fi
log_success "Resource group verified: $RESOURCE_GROUP"

# Get apps in resource group
echo ""
log_info "Available Static Web Apps:"

APP_LIST=$(az staticwebapp list --resource-group "$RESOURCE_GROUP" --query "[].{name:name, location:location}" -o json 2>/dev/null || echo "[]")
APP_COUNT=$(echo "$APP_LIST" | jq 'length')

if [ "$APP_COUNT" -eq 0 ]; then
  log_warning "No Static Web Apps found in this resource group"
  echo "Enter the name to create or use:"
else
  echo "$APP_LIST" | jq -r '.[] | "  \(.name) (location: \(.location))"'
fi

echo ""
read -p "Enter Static Web App name: " STATIC_WEB_APP_NAME

# ============================================================================
# Create config file
# ============================================================================
CONFIG_FILE=".azure/config.env"

echo ""
log_info "Creating configuration file: $CONFIG_FILE"

cat > "$CONFIG_FILE" << EOF
# Azure Deployment Configuration
# Generated by init-config.sh on $(date)
# DO NOT COMMIT TO GIT - Add to .gitignore

AZURE_SUBSCRIPTION_ID="$SUB_ID"
AZURE_RESOURCE_GROUP="$RESOURCE_GROUP"
AZURE_STATIC_WEB_APP="$STATIC_WEB_APP_NAME"
AZURE_REGION="eastus2"  # Change if needed
AZURE_BUILD_DIR="./dist"
AZURE_APP_LOCATION="/"
AZURE_OUTPUT_LOCATION="dist"
EOF

chmod 600 "$CONFIG_FILE"
log_success "Configuration file created"

echo ""
log_success "Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Review configuration: cat $CONFIG_FILE"
echo "  2. Ensure $CONFIG_FILE is in .gitignore"
echo "  3. Deploy: ./.azure/deploy-swa.sh"
echo ""

exit 0
